In [1]:
import numpy

In [3]:
print(numpy.arange(5))

[0 1 2 3 4]


In [8]:
list_2D = [[1,2,3],[123]]
# convert a python list into a numpy array:
list_2D_array = numpy.asarray(list_2D)
print(list_2D_array)
list_2D_array

[list([1, 2, 3]) list([123])]


array([list([1, 2, 3]), list([123])], dtype=object)

In [1]:
import cv2

In [2]:
# create an image as array
# 0: reading the img in gayscale, 1:RGB
img_gray = cv2.imread("smallgray.png", 0)
img_gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
#create image out of python array:
cv2.imwrite("newpic.png", img_gray)

True

In [5]:
# to iterate through a numpy array in colums:
for i in img_gray.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [6]:
# to iterate through a numpy array in rows:
for i in img_gray:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [9]:
# accessing values in numpy array one by one:
for i in img_gray.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
